export const SONG_LIST_REQUEST = "SONG_LIST_REQUEST"
export const SONG_LIST_SUCCESS = "SONG_LIST_SUCCESS"
export const SONG_LIST_FAIL = "SONG_LIST_FAIL"

export const SONG_DETAILS_REQUEST = "SONG_DETAILS_REQUEST"
export const SONG_DETAILS_SUCCESS = "SONG_DETAILS_SUCCESS"
export const SONG_DETAILS_FAIL = "SONG_DETAILS_FAIL"

export const SONG_CREATE_REVIEW_REQUEST = "SONG_CREATE_REVIEW_REQUEST"
export const SONG_CREATE_REVIEW_SUCCESS = "SONG_CREATE_REVIEW_SUCCESS"
export const SONG_CREATE_REVIEW_FAIL = "SONG_CREATE_REVIEW_FAIL"
export const SONG_CREATE_REVIEW_RESET = "SONG_CREATE_REVIEW_RESET"

export const SONG_ADD_LIKE_REQUEST = "SONG_ADD_LIKE_REQUEST"
export const SONG_ADD_LIKE_SUCCESS = "SONG_ADD_LIKE_SUCCESS"
export const SONG_ADD_LIKE_FAIL = "SONG_ADD_LIKE_FAIL"
export const SONG_ADD_LIKE_RESET = "SONG_ADD_LIKE_RESET"